{
  "nixpacks": {
    "phases": {
      "setup": {
        "nixPkgs": ["python39"]
      },
      "install": {
        "cmds": [
          "pip install -r requirements.txt"
        ]
      }
    }
  }
}
